null_matrix <- matrix(0, nrow = 3, ncol = 3)
print(null_matrix)
square_matrix <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3, ncol = 3)
print(square_matrix)
diagonal_matrix <- diag(1:5)
print(diagonal_matrix)
upper_triangular_matrix <- matrix(c(1, 2, 3, 0, 5, 6, 0, 0, 9), nrow = 3, ncol = 3, byrow = TRUE)
print(upper_triangular_matrix)
lower_triangular_matrix <- matrix(c(1, 0, 0, 4, 5, 0, 7, 8, 9), nrow = 3, ncol = 3, byrow = TRUE)
print(lower_triangular_matrix)
symmetric_matrix <- matrix(c(1, 2, 3, 2, 4, 5, 3, 5, 6), nrow = 3, ncol = 3, byrow = TRUE)
print(symmetric_matrix)
antisymmetric_matrix <- matrix(c(0, 2, 3, -2, 0, 5, -3, -5, 0), nrow = 3, ncol = 3, byrow = TRUE)
print(antisymmetric_matrix)
